# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Conditional Image Generation
description: > # ignore new line until baseurl:
  In this project we try to reconstruct the inner part
  of an image given the outer part of it and a sentence
  that describes the image. The inner part that must be
  reconstructed is a square of 32x32 pixels and the total
  image size is 64x64 pixels.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  GabrielBernard

# gems
gems:
  - jekyll-pandoc
# Build settings
markdown: kramdown
# markdown: Pandoc
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

# Pandoc options
pandoc:
  extensions:
    - normalize
    - smart
    - bibliography: bibliography/bibliography.bib
